name: release binary
on:
  push:
    branches:
      - release
      - actions/release
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
  pull_request:
    branches:
      - release
      - actions/release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
            host: macos-latest
            workdir: /Users/runner/work/numeronym/numeronym
          - target: x86_64-apple-darwin
            host: macos-latest
            workdir: /Users/runner/work/numeronym/numeronym
          - target: x86_64-unknown-linux-musl
            host: ubuntu-latest
            workdir: /home/runner/work/numeronym/numeronym
          - target: aarch64-unknown-linux-musl
            host: ubuntu-latest
            workdir: /home/runner/work/numeronym/numeronym

    steps:
      - uses: actions/checkout@master
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}
      - name: compress binary
        run: zip ${{ matrix.workdir }}/numeronym_${{ matrix.target }}.zip target/${{ matrix.target }}/release/numeronym
      - name: Upload artifact
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.workdir }}/numeronym_${{ matrix.target }}.zip
          asset_name: numeronym_${{ matrix.target }}.zip
          tag: ${{ github.ref }}
          overwrite: false
          body: ${{ github.event.head_commit.message }}

